first_lesson/sampleapp/sampleapp/urls.py
from django.contrib import admin
from django.urls import path,include
from snippets import urls

urlpatterns = [
    path('snippets/',include('snippets.urls', namespace='snippets')),
    path('admin/', admin.site.urls),
]

first_lesson/sampleapp/snippets/urls.py
from django.urls import path,include
from . import views

app_name='snippets'
urlpatterns = [
    path('',views.snippets_list, name='list'),
    path('<int:id>/', views.snippets_details, name='details'),
]

first_lesson/sampleapp/snippets/models.py
from django.db import models

# Create your models here.

first_lesson/sampleapp/snippets/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.urls import reverse

# Create your views here.
def snippets_list(request):
    name =[ 'bob', 'jackson', 'leo', 'maz']
    is_expired = False
    return render(request, 'snippets/snippets_list.html', {'name_key':name, 'is_expired':is_expired})

def snippets_details(request, id):
    return HttpResponse(f'snippets_favourite with id of {id}')

first_lesson/sampleapp/templates/snippets/_box.html
<div class="" style="background-color: blue; width: 100px; height:100px">
</div>

first_lesson/sampleapp/templates/snippets/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>{% block title %}{% endblock title %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static "snippets/styles.css" %}" type="text/css">

    </head>
    <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

    <div class="container">
        <h1>Snippet</h1>
        <div class="jumbotron">
            {% block content %}
             <h2>From Base </h2>
            {% endblock content %}
        </div>

    </div>
    </body>
</html>

first_lesson/sampleapp/templates/snippets/snippets_list.html
{% extends 'snippets/base.html' %}


{% block title %} Snippets Title {% endblock %}


{% block content %}

<h1>Welcome to the  Snippet List </h1>
<h2>This is Snippets list page:</h2>
{% for name in name_key %}
    <h3>{{ name|upper }}</h3>
{% empty %}
 <h4>No elements found!!</h4>
{% endfor %}

{% if is_expired %}
        <a href="{% url 'snippets:details' id=1 %}">Click me</a>
{% else %}
    <h1>Not expired </h1>
{% endif %}


{% endblock content %}